@startuml

title __APP's Class Diagram__\n

  namespace com.stats.umer.stats {
    class com.stats.umer.stats.BuildConfig {
    }
  }
  

  namespace com.stats.umer.stats {
    class com.stats.umer.stats.CallbackDataParser {
    }
  }
  

  namespace com.stats.umer.stats {
    interface com.stats.umer.stats.CallbackInterface {
    }
  }
  

  namespace com.stats.umer.stats {
    namespace activity {
      class com.stats.umer.stats.activity.LocationActivity_ViewBinding {
      }
    }
  }
  

  namespace com.stats.umer.stats {
    namespace activity {
      class com.stats.umer.stats.activity.LoginActivity_ViewBinding {
      }
    }
  }
  

  namespace com.stats.umer.stats {
    namespace activity {
      class com.stats.umer.stats.activity.ParentHomeScreenActivity_ViewBinding {
      }
    }
  }
  

  namespace com.stats.umer.stats {
    namespace activity {
      class com.stats.umer.stats.activity.ReportIssueActivity_ViewBinding {
      }
    }
  }
  

  namespace com.stats.umer.stats {
    namespace activity {
      class com.stats.umer.stats.activity.StopListActivity_ViewBinding {
      }
    }
  }
  

  namespace com.stats.umer.stats {
    namespace activity {
      class com.stats.umer.stats.activity.StudnetHomeScreenActivity_ViewBinding {
      }
    }
  }
  

  namespace com.stats.umer.stats {
    namespace adapter {
      class com.stats.umer.stats.adapter.BusStopPointsRecyclerViewAdapter$BusStopPointsItemViewHolder_ViewBinding {
      }
    }
  }
  

  com.stats.umer.stats.CallbackDataParser o-- T : data
  com.stats.umer.stats.CallbackDataParser o-- com.stats.umer.stats.Enum.ServerStatusCodes : status
  com.stats.umer.stats.activity.LocationActivity_ViewBinding .up.|> butterknife.Unbinder
  com.stats.umer.stats.activity.LocationActivity_ViewBinding o-- com.stats.umer.stats.activity.LocationActivity : target
  com.stats.umer.stats.activity.LoginActivity_ViewBinding .up.|> butterknife.Unbinder
  com.stats.umer.stats.activity.LoginActivity_ViewBinding o-- com.stats.umer.stats.activity.LoginActivity : target
  com.stats.umer.stats.activity.ParentHomeScreenActivity_ViewBinding .up.|> butterknife.Unbinder
  com.stats.umer.stats.activity.ParentHomeScreenActivity_ViewBinding o-- com.stats.umer.stats.activity.ParentHomeScreenActivity : target
  com.stats.umer.stats.activity.ReportIssueActivity_ViewBinding .up.|> butterknife.Unbinder
  com.stats.umer.stats.activity.ReportIssueActivity_ViewBinding o-- com.stats.umer.stats.activity.ReportIssueActivity : target
  com.stats.umer.stats.activity.StopListActivity_ViewBinding .up.|> butterknife.Unbinder
  com.stats.umer.stats.activity.StopListActivity_ViewBinding o-- com.stats.umer.stats.activity.StopListActivity : target
  com.stats.umer.stats.activity.StudnetHomeScreenActivity_ViewBinding .up.|> butterknife.Unbinder
  com.stats.umer.stats.activity.StudnetHomeScreenActivity_ViewBinding o-- com.stats.umer.stats.activity.StudnetHomeScreenActivity : target
  com.stats.umer.stats.adapter.BusStopPointsRecyclerViewAdapter$BusStopPointsItemViewHolder_ViewBinding .up.|> butterknife.Unbinder
  com.stats.umer.stats.adapter.BusStopPointsRecyclerViewAdapter$BusStopPointsItemViewHolder_ViewBinding o-- com.stats.umer.stats.adapter.BusStopPointsRecyclerViewAdapter.BusStopPointsItemViewHolder : target


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
